name: CMake

on:
  push:
    branches: [ task5 ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      shell: bash
      
      working-directory: ${{github.workspace}}/task5
      # run: tree; echo "hello world"
      run: git clone https://github.com/google/googletest.git; mv googletest 3rdparty; mkdir build; cd build; cmake ..; cmake --build .
      
    - name: Test
      uses: akhtyamovpavel/ActionGtestReport@v0.0.9
      with:
        exec-path: "CTestExe"
        report-path: "bin/test.test"
        working-directory: "bin/"

    - name: tree
      shell: bash
      working-directory: ${{github.workspace}}/task5
      run: tree; ./bin/CTestExe

      
#     - name: something
#       shell: bash
      
#       working-directory: ${{github.workspace}}
#       run: git clone https://github.com/akhtyamovpavel/ActionGtestReport.git; cd ActionGtestReport; npm install; node index.js
      
