name: CMake

on:
  push:
    branches: [ task5 ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      shell: bash
      
      working-directory: ${{github.workspace}}/task5/build
      # run: tree; echo "hello world"
      run: mkdir task5/build; cmake $GITHUB_WORKSPACE/task5; cmake --build; cmake --install
      
    - name: something
      run: echo "hehe"
